In [1]:
import pandas as pd
import numpy as np

In [2]:
# now here i am going to load data file
data = pd.read_csv(r"C:\Users\Prashant\Desktop\collegedata\Test2dataset\test2.csv")

In [3]:
data=data.drop("Date",axis=1)

In [4]:
data.head()

,user,Email address,I like to work on cars,I like to do puzzles,I am good at working independently,I like to work in teams,"I am an ambitious person, I set goals for myself","I like to organize things, (files, desks/offices)",I like to build things,I like to read about art and music,...,Unnamed: 34,I like to get into discussions,I am good at keeping records of my work,I like to lead,I like working outdoors,I would like to work in an office,I’m good at math,I like helping people,I like to draw,I like to give speeches
0,19241A0101 19241A0101,ruhaillone007@gmail.com,Yes,YES,YES,NO,YES,NO,YES,YES,...,NO,NO,NO,NO,YES,NO,NO,NO,NO,NO
1,19241A0102 19241A0102,asaiteja883@gmail.com,Yes,NO,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,YES,YES,YES,YES
2,19241A0103 19241A0103,barishettyshiva@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,NO,NO,YES,YES,YES,NO,YES,YES,YES,NO
3,19241A0104 19241A0104,varuntej.1704@gmail.com,No,NO,YES,YES,YES,YES,YES,YES,...,NO,YES,YES,YES,YES,NO,NO,YES,YES,YES
4,19241A0105 19241A0105,vamshinayak460@gmail.com,No,YES,YES,YES,YES,YES,YES,YES,...,NO,YES,NO,YES,YES,NO,YES,YES,NO,YES

In [5]:
# now i have done  cleaning of user name

In [6]:
newdata = pd.read_excel(r"C:\Users\Prashant\Desktop\collegedata\Test2dataset\final.xlsx")

In [7]:
newdata.head()

,User full name,Email address,one,two,three,four,five,six,seven,eight,...,thirtythree,thirtyfour,thirtyfive,thirtysix,thirtyseven,thirtyeight,thirtynine,fourty,fourtyone,fourtytwo
0,19241A0101,ruhaillone007@gmail.com,Yes,YES,YES,NO,YES,NO,YES,YES,...,NO,NO,NO,NO,YES,NO,NO,NO,NO,NO
1,19241A0102,asaiteja883@gmail.com,Yes,NO,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,YES,YES,YES,YES
2,19241A0103,barishettyshiva@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,NO,NO,YES,YES,YES,NO,YES,YES,YES,NO
3,19241A0104,varuntej.1704@gmail.com,No,NO,YES,YES,YES,YES,YES,YES,...,NO,YES,YES,YES,YES,NO,NO,YES,YES,YES
4,19241A0105,vamshinayak460@gmail.com,No,YES,YES,YES,YES,YES,YES,YES,...,NO,YES,NO,YES,YES,NO,YES,YES,NO,YES

In [8]:
newdata.index = np.arange(1, len(newdata) + 1) # this is to rename row index from 1

In [9]:
# if you want to do for columms
# df.columns += 1

In [10]:
newdata

,User full name,Email address,one,two,three,four,five,six,seven,eight,...,thirtythree,thirtyfour,thirtyfive,thirtysix,thirtyseven,thirtyeight,thirtynine,fourty,fourtyone,fourtytwo
1,19241A0101,ruhaillone007@gmail.com,Yes,YES,YES,NO,YES,NO,YES,YES,...,NO,NO,NO,NO,YES,NO,NO,NO,NO,NO
2,19241A0102,asaiteja883@gmail.com,Yes,NO,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,YES,YES,YES,YES
3,19241A0103,barishettyshiva@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,NO,NO,YES,YES,YES,NO,YES,YES,YES,NO
4,19241A0104,varuntej.1704@gmail.com,No,NO,YES,YES,YES,YES,YES,YES,...,NO,YES,YES,YES,YES,NO,NO,YES,YES,YES
5,19241A0105,vamshinayak460@gmail.com,No,YES,YES,YES,YES,YES,YES,YES,...,NO,YES,NO,YES,YES,NO,YES,YES,NO,YES
6,19241A0107,praneethk243@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,YES,YES,YES,YES
7,19241A0108,rahulchiluka2511@gmail.com,Yes,YES,YES,NO,YES,NO,YES,YES,...,NO,YES,YES,YES,YES,NO,YES,YES,YES,NO
8,19241A0110,ragneshdayya@gmail.com,No,YES,YES,YES,YES,YES,NO,NO,...,NO,YES,YES,NO,NO,YES,YES,YES,YES,YES
9,19241A0111,manishgoud3255@gmail.com,Yes,YES,NO,YES,NO,YES,YES,NO,...,NO,YES,NO,YES,YES,YES,NO,YES,YES,YES
10,19241A0112,saipriyaerram@gmail.com,No,YES,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,NO,YES,YES,YES
11,19241A0113,deepika888113@gmail.com,Yes,YES,NO,YES,YES,YES,YES,YES,...,NO,NO,NO,YES,YES,YES,NO,YES,NO,NO
12,19241A0114,saigorantala457@gmail.com,No,YES,YES,YES,YES,NO,YES,NO,...,YES,YES,YES,YES,YES,NO,YES,YES,NO,YES
13,19241A0115,santhosh63054@gmail.com,No,YES,YES,YES,YES,YES,YES,NO,...,YES,YES,YES,YES,NO,NO,YES,YES,YES,YES
14,19241A0116,saigurijala19@gmail.com,Yes,YES,YES,YES,YES,NO,YES,YES,...,YES,YES,YES,YES,YES,NO,YES,YES,YES,NO
15,19241A0117,gurujalasridhar2001@gmail.com,No,YES,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,YES,YES,YES,YES
16,19241A0118,hemanthkumariruvanti@gmail.com,No,YES,NO,YES,YES,YES,YES,NO,...,YES,YES,YES,YES,YES,YES,YES,YES,NO,YES
17,19241A0119,dharmaiahjangiti09@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,YES,YES,YES,YES
18,19241A0120,cheran1707@gmail.com,Yes,NO,NO,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,NO,YES,NO,YES
19,19241A0121,naveenjatoth942@gmail.com,No,YES,NO,YES,YES,YES,YES,NO,...,YES,YES,NO,YES,YES,NO,YES,YES,NO,NO
20,19241A0122,jettisreevani@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,YES,YES,YES,YES
21,19241A0123,sowmyasweety83@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,YES,YES,YES,YES
22,19241A0124,kksrisai02@gmail.com,No,YES,YES,YES,YES,YES,YES,YES,...,NO,YES,YES,YES,YES,NO,YES,YES,YES,NO
23,19241A0125,kamareddyakshay7@gmail.com,Yes,NO,YES,YES,YES,YES,YES,NO,...,YES,NO,NO,YES,YES,NO,YES,YES,NO,YES
24,19241A0126,ksai61587@gmail.com,No,YES,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,NO,YES,YES,YES,YES,YES,YES
25,19241A0127,tejaswikolluri14@gmail.com,No,YES,YES,YES,YES,YES,YES,YES,...,NO,YES,YES,YES,NO,YES,YES,YES,YES,YES
26,19241A0129,vivekkotte111@gmail.com,Yes,YES,YES,YES,YES,NO,YES,NO,...,YES,NO,YES,NO,YES,YES,YES,YES,YES,NO
27,19241A0130,kruthikapalange@gmail.com,No,YES,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,NO,YES,YES,YES,YES
28,19241A0131,madaakhilreddy@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,NO,YES,YES,NO
29,19241A0132,reddyshravankumar25@gamil.com,Yes,YES,NO,YES,YES,NO,YES,YES,...,NO,YES,YES,YES,YES,NO,YES,YES,NO,YES
30,19241A0133,maddigatlaajaysagar02@gmail.com,Yes,NO,YES,NO,YES,YES,YES,YES,...,NO,YES,YES,YES,YES,NO,NO,YES,YES,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,19241A12E7,varshithvarshi7@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,YES,YES,YES,YES
929,19241A12E8,keshavagarinikitha262@gmail.com,No,YES,NO,YES,YES,YES,YES,NO,...,NO,NO,YES,YES,YES,NO,NO,YES,YES,NO
930,19241A12E9,sampathreddy2737@gmail.com,No,YES,YES,NO,YES,YES,YES,NO,...,YES,YES,YES,YES,YES,YES,YES,YES,NO,YES
931,19241A12F0,shivashiva43394@gmail.com,Yes,YES,NO,YES,YES,YES,YES,YES,...,YES,YES,YES,NO,YES,YES,YES,YES,NO,YES
932,19241A12F1,reddyjayram529@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,NO,YES,YES,YES,YES,YES,YES,YES,YES,NO
933,19241A12F4,lsathwikareddy@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,YES,YES,NO,NO
934,19241A12F5,mchandrareddy1177@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,YES,YES,YES,YES
935,19241A12F6,aishwaryamadapathi009@gmail.com,Yes,YES,NO,YES,YES,YES,YES,YES,...,YES,NO,NO,YES,YES,NO,NO,YES,YES,YES
936,19241A12F7,sitaramamaddikara@gmail.com,Yes,YES,YES,YES,YES,NO,YES,NO,...,NO,YES,YES,YES,YES,NO,YES,YES,NO,NO
937,19241A12F8,mahajan.vamshisai@gmail.com,No,YES,YES,YES,YES,YES,YES,YES,...,NO,YES,YES,NO,YES,YES,YES,YES,YES,YES
938,19241A12F9,sirimankena@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,NO,NO,YES,YES,YES,NO,NO,YES,YES,NO
939,19241A12G0,dileep28702@gmail.com,Yes,YES,NO,YES,YES,YES,YES,NO,...,YES,YES,YES,YES,YES,YES,YES,YES,YES,NO
940,19241A12G1,morampudiabhilash@gmail.com,Yes,NO,YES,NO,YES,NO,YES,NO,...,YES,YES,YES,YES,YES,NO,NO,YES,NO,YES
941,19241A12G2,mysaakash125@gmail.com,Yes,YES,NO,YES,NO,NO,NO,YES,...,YES,YES,YES,YES,YES,NO,YES,YES,NO,YES
942,19241A12G3,preethi.nacham@gmail.com,No,YES,NO,YES,YES,YES,YES,YES,...,NO,YES,YES,NO,YES,YES,YES,YES,YES,NO
943,19241A12G4,madhavanneerati289@gmail.com,No,YES,NO,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,NO,YES,YES,NO
944,19241A12G5,kumudininerella119@gmail.com,Yes,YES,YES,YES,YES,NO,YES,NO,...,NO,YES,NO,YES,YES,YES,YES,YES,YES,NO
945,19241A12G6,polladivya@gmail.com,Yes,YES,YES,YES,YES,NO,YES,NO,...,NO,YES,YES,YES,YES,YES,NO,YES,YES,YES
946,19241A12G8,ravillags@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,NO,YES,NO,YES,YES,NO,NO,YES,YES,NO
947,19241A12H0,sapavathpavana@gmail.com,No,YES,YES,YES,YES,NO,YES,YES,...,YES,YES,YES,YES,NO,YES,YES,YES,YES,YES
948,19241A12H1,sasanapurisnehitha@gmail.com,No,YES,YES,NO,NO,YES,YES,YES,...,YES,YES,YES,NO,NO,YES,YES,YES,YES,NO
949,19241A12H2,abbasmiya.shaik@gmail.com,Yes,YES,NO,YES,NO,YES,YES,YES,...,NO,YES,YES,YES,YES,NO,NO,YES,YES,YES
950,19241A12H4,adithisoppadandi@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,NO,YES,YES,YES,YES,NO,YES,YES,YES,YES
951,19241A12H5,nandinitumma12@gmail.com,Yes,YES,NO,YES,YES,NO,YES,NO,...,NO,NO,NO,YES,YES,YES,YES,NO,NO,NO
952,19241A12H6,1956narayana@gmail.com,No,YES,NO,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,YES,YES,YES,NO
953,19241A12H7,vaaparna2001@gmail.com,No,YES,YES,YES,YES,NO,YES,NO,...,YES,YES,NO,YES,NO,YES,YES,YES,YES,YES
954,19241A12H8,vjagan417@gmail.com,Yes,NO,YES,YES,NO,NO,YES,YES,...,YES,YES,YES,YES,YES,YES,YES,YES,NO,YES
955,19241A12H9,vyamasanishreya@gmail.com,No,YES,YES,NO,YES,YES,YES,YES,...,NO,NO,YES,YES,YES,YES,NO,YES,YES,YES
956,19241A12I0,akshitharinky44@gmail.com,Yes,YES,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,YES,YES,YES,YES
957,Admin,admin@griet.ac.in,No,NO,NO,NO,YES,YES,YES,YES,...,YES,YES,NO,NO,YES,YES,YES,YES,YES,YES

In [11]:
 newdata['one']=pd.Series(map(lambda x: dict(Yes=1, No=0)[x],newdata.one.values.tolist()), newdata.index)

In [12]:
newdata.head()

,User full name,Email address,one,two,three,four,five,six,seven,eight,...,thirtythree,thirtyfour,thirtyfive,thirtysix,thirtyseven,thirtyeight,thirtynine,fourty,fourtyone,fourtytwo
1,19241A0101,ruhaillone007@gmail.com,1,YES,YES,NO,YES,NO,YES,YES,...,NO,NO,NO,NO,YES,NO,NO,NO,NO,NO
2,19241A0102,asaiteja883@gmail.com,1,NO,YES,YES,YES,YES,YES,YES,...,YES,YES,YES,YES,YES,YES,YES,YES,YES,YES
3,19241A0103,barishettyshiva@gmail.com,1,YES,YES,YES,YES,YES,YES,YES,...,NO,NO,YES,YES,YES,NO,YES,YES,YES,NO
4,19241A0104,varuntej.1704@gmail.com,0,NO,YES,YES,YES,YES,YES,YES,...,NO,YES,YES,YES,YES,NO,NO,YES,YES,YES
5,19241A0105,vamshinayak460@gmail.com,0,YES,YES,YES,YES,YES,YES,YES,...,NO,YES,NO,YES,YES,NO,YES,YES,NO,YES

In [67]:
for column in newdata.columns[3:50]:
    #print(newdata[column])
    newdata = newdata.replace(to_replace = "YES", value = 1)
    newdata = newdata.replace(to_replace = "NO", value = 0)

In [14]:
newdata
newdata['Relastic'] = newdata['one']+newdata['seven']+newdata['fourteen']+newdata['tweentytwo']+newdata['thirtytwo']+newdata['thirtyseven']

In [15]:
newdata['Investigative']=newdata['two']+newdata['eleven']+newdata['eighteen']+newdata['twentyone']+newdata['thirtythree']+newdata['thirtynine']

In [16]:
newdata.head()

,User full name,Email address,one,two,three,four,five,six,seven,eight,...,thirtyfive,thirtysix,thirtyseven,thirtyeight,thirtynine,fourty,fourtyone,fourtytwo,Relastic,Investigative
1,19241A0101,ruhaillone007@gmail.com,1,1,1,0,1,0,1,1,...,0,0,1,0,0,0,0,0,5,3
2,19241A0102,asaiteja883@gmail.com,1,0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,6,4
3,19241A0103,barishettyshiva@gmail.com,1,1,1,1,1,1,1,1,...,1,1,1,0,1,1,1,0,6,5
4,19241A0104,varuntej.1704@gmail.com,0,0,1,1,1,1,1,1,...,1,1,1,0,0,1,1,1,5,2
5,19241A0105,vamshinayak460@gmail.com,0,1,1,1,1,1,1,1,...,0,1,1,0,1,1,0,1,3,5

In [17]:
newdata['Artistic']=newdata['three']+newdata['eight']+newdata['seventeen']+newdata['tweentythree']+newdata['tweentyseven']+newdata['thirtyone']+newdata['fourtyone']

In [18]:
newdata.head()

,User full name,Email address,one,two,three,four,five,six,seven,eight,...,thirtysix,thirtyseven,thirtyeight,thirtynine,fourty,fourtyone,fourtytwo,Relastic,Investigative,Artistic
1,19241A0101,ruhaillone007@gmail.com,1,1,1,0,1,0,1,1,...,0,1,0,0,0,0,0,5,3,4
2,19241A0102,asaiteja883@gmail.com,1,0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,6,4,7
3,19241A0103,barishettyshiva@gmail.com,1,1,1,1,1,1,1,1,...,1,1,0,1,1,1,0,6,5,6
4,19241A0104,varuntej.1704@gmail.com,0,0,1,1,1,1,1,1,...,1,1,0,0,1,1,1,5,2,6
5,19241A0105,vamshinayak460@gmail.com,0,1,1,1,1,1,1,1,...,1,1,0,1,1,0,1,3,5,6

In [19]:
newdata['social']=newdata['four']+newdata['twelve']+newdata['Thirteen']+newdata['twenty']+newdata['tweentyeight']+newdata['thirtyfour']+newdata['fourty']

In [20]:
newdata.head()

,User full name,Email address,one,two,three,four,five,six,seven,eight,...,thirtyseven,thirtyeight,thirtynine,fourty,fourtyone,fourtytwo,Relastic,Investigative,Artistic,social
1,19241A0101,ruhaillone007@gmail.com,1,1,1,0,1,0,1,1,...,1,0,0,0,0,0,5,3,4,2
2,19241A0102,asaiteja883@gmail.com,1,0,1,1,1,1,1,1,...,1,1,1,1,1,1,6,4,7,7
3,19241A0103,barishettyshiva@gmail.com,1,1,1,1,1,1,1,1,...,1,0,1,1,1,0,6,5,6,5
4,19241A0104,varuntej.1704@gmail.com,0,0,1,1,1,1,1,1,...,1,0,0,1,1,1,5,2,6,7
5,19241A0105,vamshinayak460@gmail.com,0,1,1,1,1,1,1,1,...,1,0,1,1,0,1,3,5,6,7

In [21]:
newdata['Enterprising'] = newdata['five']+newdata['ten']+newdata['sixteen']+newdata['nineteen']+newdata['tweentynine']+newdata['thirtysix']+newdata['fourtytwo']

In [22]:
newdata.head()

,User full name,Email address,one,two,three,four,five,six,seven,eight,...,thirtyeight,thirtynine,fourty,fourtyone,fourtytwo,Relastic,Investigative,Artistic,social,Enterprising
1,19241A0101,ruhaillone007@gmail.com,1,1,1,0,1,0,1,1,...,0,0,0,0,0,5,3,4,2,3
2,19241A0102,asaiteja883@gmail.com,1,0,1,1,1,1,1,1,...,1,1,1,1,1,6,4,7,7,6
3,19241A0103,barishettyshiva@gmail.com,1,1,1,1,1,1,1,1,...,0,1,1,1,0,6,5,6,5,4
4,19241A0104,varuntej.1704@gmail.com,0,0,1,1,1,1,1,1,...,0,0,1,1,1,5,2,6,7,6
5,19241A0105,vamshinayak460@gmail.com,0,1,1,1,1,1,1,1,...,0,1,1,0,1,3,5,6,7,6

In [23]:
newdata['conventional']=newdata['six']+newdata['nine']+newdata['fifteen']+newdata['tweentyfour']+newdata['tweentyfive']+newdata['thirtyfive']+newdata['thirtyeight']

In [24]:
newdata.head()

,User full name,Email address,one,two,three,four,five,six,seven,eight,...,thirtynine,fourty,fourtyone,fourtytwo,Relastic,Investigative,Artistic,social,Enterprising,conventional
1,19241A0101,ruhaillone007@gmail.com,1,1,1,0,1,0,1,1,...,0,0,0,0,5,3,4,2,3,2
2,19241A0102,asaiteja883@gmail.com,1,0,1,1,1,1,1,1,...,1,1,1,1,6,4,7,7,6,7
3,19241A0103,barishettyshiva@gmail.com,1,1,1,1,1,1,1,1,...,1,1,1,0,6,5,6,5,4,6
4,19241A0104,varuntej.1704@gmail.com,0,0,1,1,1,1,1,1,...,0,1,1,1,5,2,6,7,6,5
5,19241A0105,vamshinayak460@gmail.com,0,1,1,1,1,1,1,1,...,1,1,0,1,3,5,6,7,6,3

In [25]:
newdata

,User full name,Email address,one,two,three,four,five,six,seven,eight,...,thirtynine,fourty,fourtyone,fourtytwo,Relastic,Investigative,Artistic,social,Enterprising,conventional
1,19241A0101,ruhaillone007@gmail.com,1,1,1,0,1,0,1,1,...,0,0,0,0,5,3,4,2,3,2
2,19241A0102,asaiteja883@gmail.com,1,0,1,1,1,1,1,1,...,1,1,1,1,6,4,7,7,6,7
3,19241A0103,barishettyshiva@gmail.com,1,1,1,1,1,1,1,1,...,1,1,1,0,6,5,6,5,4,6
4,19241A0104,varuntej.1704@gmail.com,0,0,1,1,1,1,1,1,...,0,1,1,1,5,2,6,7,6,5
5,19241A0105,vamshinayak460@gmail.com,0,1,1,1,1,1,1,1,...,1,1,0,1,3,5,6,7,6,3
6,19241A0107,praneethk243@gmail.com,1,1,1,1,1,1,1,1,...,1,1,1,1,6,6,6,7,6,7
7,19241A0108,rahulchiluka2511@gmail.com,1,1,1,0,1,0,1,1,...,1,1,1,0,5,5,6,5,5,3
8,19241A0110,ragneshdayya@gmail.com,0,1,1,1,1,1,0,0,...,1,1,1,1,1,5,6,5,3,6
9,19241A0111,manishgoud3255@gmail.com,1,1,0,1,0,1,1,0,...,0,1,1,1,6,4,4,7,6,4
10,19241A0112,saipriyaerram@gmail.com,0,1,1,1,1,1,1,1,...,0,1,1,1,5,5,6,7,7,5
11,19241A0113,deepika888113@gmail.com,1,1,0,1,1,1,1,1,...,0,1,0,0,5,3,2,6,4,5
12,19241A0114,saigorantala457@gmail.com,0,1,1,1,1,0,1,0,...,1,1,0,1,3,6,4,6,6,1
13,19241A0115,santhosh63054@gmail.com,0,1,1,1,1,1,1,0,...,1,1,1,1,4,6,6,6,6,4
14,19241A0116,saigurijala19@gmail.com,1,1,1,1,1,0,1,1,...,1,1,1,0,5,5,7,7,3,3
15,19241A0117,gurujalasridhar2001@gmail.com,0,1,1,1,1,1,1,1,...,1,1,1,1,5,6,7,6,6,7
16,19241A0118,hemanthkumariruvanti@gmail.com,0,1,0,1,1,1,1,0,...,1,1,0,1,5,6,2,7,5,7
17,19241A0119,dharmaiahjangiti09@gmail.com,1,1,1,1,1,1,1,1,...,1,1,1,1,6,6,7,7,7,7
18,19241A0120,cheran1707@gmail.com,1,0,0,1,1,1,1,1,...,0,1,0,1,6,4,5,7,4,7
19,19241A0121,naveenjatoth942@gmail.com,0,1,0,1,1,1,1,0,...,1,1,0,0,4,5,2,6,5,3
20,19241A0122,jettisreevani@gmail.com,1,1,1,1,1,1,1,1,...,1,1,1,1,6,6,7,6,6,7
21,19241A0123,sowmyasweety83@gmail.com,1,1,1,1,1,1,1,1,...,1,1,1,1,6,6,7,6,6,7
22,19241A0124,kksrisai02@gmail.com,0,1,1,1,1,1,1,1,...,1,1,1,0,5,5,7,7,4,5
23,19241A0125,kamareddyakshay7@gmail.com,1,0,1,1,1,1,1,0,...,1,1,0,1,3,3,5,6,6,2
24,19241A0126,ksai61587@gmail.com,0,1,1,1,1,1,1,1,...,1,1,1,1,5,6,7,7,5,6
25,19241A0127,tejaswikolluri14@gmail.com,0,1,1,1,1,1,1,1,...,1,1,1,1,4,5,7,6,7,6
26,19241A0129,vivekkotte111@gmail.com,1,1,1,1,1,0,1,0,...,1,1,1,0,6,3,4,5,2,5
27,19241A0130,kruthikapalange@gmail.com,0,1,1,1,1,1,1,1,...,1,1,1,1,3,6,7,7,6,6
28,19241A0131,madaakhilreddy@gmail.com,1,1,1,1,1,1,1,1,...,0,1,1,0,6,4,6,5,5,5
29,19241A0132,reddyshravankumar25@gamil.com,1,1,0,1,1,0,1,1,...,1,1,0,1,6,5,5,5,6,5
30,19241A0133,maddigatlaajaysagar02@gmail.com,1,0,1,0,1,1,1,1,...,0,1,1,0,4,3,6,6,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,19241A12E7,varshithvarshi7@gmail.com,1,1,1,1,1,1,1,1,...,1,1,1,1,6,6,7,7,7,7
929,19241A12E8,keshavagarinikitha262@gmail.com,0,1,0,1,1,1,1,0,...,0,1,1,0,4,4,5,5,4,5
930,19241A12E9,sampathreddy2737@gmail.com,0,1,1,0,1,1,1,0,...,1,1,0,1,4,6,2,6,6,6
931,19241A12F0,shivashiva43394@gmail.com,1,1,0,1,1,1,1,1,...,1,1,0,1,6,6,5,6,5,6
932,19241A12F1,reddyjayram529@gmail.com,1,1,1,1,1,1,1,1,...,1,1,1,0,6,5,7,7,5,7
933,19241A12F4,lsathwikareddy@gmail.com,1,1,1,1,1,1,1,1,...,1,1,0,0,6,6,5,7,6,7
934,19241A12F5,mchandrareddy1177@gmail.com,1,1,1,1,1,1,1,1,...,1,1,1,1,6,6,7,7,7,7
935,19241A12F6,aishwaryamadapathi009@gmail.com,1,1,0,1,1,1,1,1,...,0,1,1,1,6,5,6,6,6,3
936,19241A12F7,sitaramamaddikara@gmail.com,1,1,1,1,1,0,1,0,...,1,1,0,0,6,5,3,5,5,4
937,19241A12F8,mahajan.vamshisai@gmail.com,0,1,1,1,1,1,1,1,...,1,1,1,1,4,5,6,5,4,6
938,19241A12F9,sirimankena@gmail.com,1,1,1,1,1,1,1,1,...,0,1,1,0,5,4,7,3,4,5
939,19241A12G0,dileep28702@gmail.com,1,1,0,1,1,1,1,0,...,1,1,1,0,5,6,2,7,5,6
940,19241A12G1,morampudiabhilash@gmail.com,1,0,1,0,1,0,1,0,...,0,1,0,1,5,2,2,6,7,3
941,19241A12G2,mysaakash125@gmail.com,1,1,0,1,0,0,0,1,...,1,1,0,1,5,4,3,6,5,4
942,19241A12G3,preethi.nacham@gmail.com,0,1,0,1,1,1,1,1,...,1,1,1,0,3,5,5,7,3,5
943,19241A12G4,madhavanneerati289@gmail.com,0,1,0,1,1,1,1,1,...,0,1,1,0,4,5,3,6,5,6
944,19241A12G5,kumudininerella119@gmail.com,1,1,1,1,1,0,1,0,...,1,1,1,0,6,4,5,6,4,4
945,19241A12G6,polladivya@gmail.com,1,1,1,1,1,0,1,0,...,0,1,1,1,5,3,5,6,6,5
946,19241A12G8,ravillags@gmail.com,1,1,1,1,1,1,1,1,...,0,1,1,0,6,4,5,6,4,4
947,19241A12H0,sapavathpavana@gmail.com,0,1,1,1,1,0,1,1,...,1,1,1,1,4,6,5,7,5,6
948,19241A12H1,sasanapurisnehitha@gmail.com,0,1,1,0,0,1,1,1,...,1,1,1,0,2,4,6,5,0,5
949,19241A12H2,abbasmiya.shaik@gmail.com,1,1,0,1,0,1,1,1,...,0,1,1,1,6,4,6,7,6,5
950,19241A12H4,adithisoppadandi@gmail.com,1,1,1,1,1,1,1,1,...,1,1,1,1,6,5,7,7,5,5
951,19241A12H5,nandinitumma12@gmail.com,1,1,0,1,1,0,1,0,...,1,0,0,0,4,2,1,2,4,5
952,19241A12H6,1956narayana@gmail.com,0,1,0,1,1,1,1,1,...,1,1,1,0,5,6,6,7,4,6
953,19241A12H7,vaaparna2001@gmail.com,0,1,1,1,1,0,1,0,...,1,1,1,1,2,6,5,7,4,4
954,19241A12H8,vjagan417@gmail.com,1,0,1,1,0,0,1,1,...,1,1,0,1,5,5,5,5,5,4
955,19241A12H9,vyamasanishreya@gmail.com,0,1,1,0,1,1,1,1,...,0,1,1,1,5,3,4,5,6,6
956,19241A12I0,akshitharinky44@gmail.com,1,1,1,1,1,1,1,1,...,1,1,1,1,5,6,7,7,6,7
957,Admin,admin@griet.ac.in,0,0,0,0,1,1,1,1,...,1,1,1,1,5,5,6,6,6,6

In [26]:
my_dict = {'Relastic':newdata['Relastic'],'Investigative':newdata['Investigative'],
          'Artistic':newdata['Artistic'],'social':newdata['social'],
          'Enterprising':newdata['Enterprising'],'conventional':newdata['conventional']}

df = pd.DataFrame(my_dict)

#temp=df.index
#maxi=df.max(axis=1)
#df.head()
#plt.scatter(x=temp,y=maxi)
print("Relastic")
Index_label_Relastic = df[df['Relastic']>df['Investigative'] | df['Artistic'] | df['social'] | df['Enterprising'] | df['conventional']].index.tolist()
print(Index_label_Relastic)
print("#######################################")
print('Investigative')
Index_label_Investigative = df[df['Investigative']>df['Relastic'] | df['Artistic'] | df['social'] | df['Enterprising'] | df['conventional']].index.tolist()
print(Index_label_Investigative)
print('#########################################')
print('Artistic')
Index_label_Artistic = df[df['Artistic']>df['Investigative'] | df['Relastic'] | df['social'] | df['Enterprising'] | df['conventional']].index.tolist()
print(Index_label_Artistic)
print('###########################################')
print('socal')
Index_label_social = df[df['social']>df['Investigative'] | df['Relastic'] | df['Artistic'] | df['Enterprising'] | df['conventional']].index.tolist()
print(Index_label_social)
print('############################################')
print('Enterprising')
Index_label_Enterprising = df[df['Enterprising']>df['Investigative'] | df['Relastic'] | df['social'] | df['Artistic'] | df['conventional']].index.tolist()
print(Index_label_Artistic)
print('Conventional')
print('############################################')
Index_label_conventional = df[df['conventional']>df['Investigative'] | df['Relastic'] | df['social'] | df['Enterprising'] | df['Artistic']].index.tolist()
print(Index_label_Artistic)
print('###########################################')

equal_label =  df[df>=5]
final_values=pd.DataFrame(equal_label[equal_label>4])
print(final_values)

Relastic
[42, 478, 505, 542]
#######################################
Investigative
[94, 162, 355, 841]
#########################################
Artistic
[106, 287, 492, 580, 722, 773, 816, 883]
###########################################
socal
[9, 35, 138, 285, 303, 319, 345, 349, 368, 384, 417, 452, 461, 462, 484, 513, 520, 559, 563, 610, 622, 637, 695, 726, 742, 842, 866, 893, 894, 920]
############################################
Enterprising
[106, 287, 492, 580, 722, 773, 816, 883]
Conventional
############################################
[106, 287, 492, 580, 722, 773, 816, 883]
###########################################
     Relastic  Investigative  Artistic  social  Enterprising  conventional
1         5.0            NaN       NaN     NaN           NaN           NaN
2         6.0            NaN       7.0     7.0           6.0           7.0
3         6.0            5.0       6.0     5.0           NaN           6.0
4         5.0            NaN       6.0     7.0           6.0           5.0
5         NaN            5.0       6.0     7.0           6.0           NaN
6         6.0            6.0       6.0     7.0           6.0           7.0
7         5.0            5.0       6.0     5.0           5.0           NaN
8         NaN            5.0       6.0     5.0           NaN           6.0
9         6.0            NaN       NaN     7.0           6.0           NaN
10        5.0            5.0       6.0     7.0           7.0           5.0
11        5.0            NaN       NaN     6.0           NaN           5.0
12        NaN            6.0       NaN     6.0           6.0           NaN
13        NaN            6.0       6.0     6.0           6.0           NaN
14        5.0            5.0       7.0     7.0           NaN           NaN
15        5.0            6.0       7.0     6.0           6.0           7.0
16        5.0            6.0       NaN     7.0           5.0           7.0
17        6.0            6.0       7.0     7.0           7.0           7.0
18        6.0            NaN       5.0     7.0           NaN           7.0
19        NaN            5.0       NaN     6.0           5.0           NaN
20        6.0            6.0       7.0     6.0           6.0           7.0
21        6.0            6.0       7.0     6.0           6.0           7.0
22        5.0            5.0       7.0     7.0           NaN           5.0
23        NaN            NaN       5.0     6.0           6.0           NaN
24        5.0            6.0       7.0     7.0           5.0           6.0
25        NaN            5.0       7.0     6.0           7.0           6.0
26        6.0            NaN       NaN     5.0           NaN           5.0
27        NaN            6.0       7.0     7.0           6.0           6.0
28        6.0            NaN       6.0     5.0           5.0           5.0
29        6.0            5.0       5.0     5.0           6.0           5.0
30        NaN            NaN       6.0     6.0           NaN           NaN
..        ...            ...       ...     ...           ...           ...
928       6.0            6.0       7.0     7.0           7.0           7.0
929       NaN            NaN       5.0     5.0           NaN           5.0
930       NaN            6.0       NaN     6.0           6.0           6.0
931       6.0            6.0       5.0     6.0           5.0           6.0
932       6.0            5.0       7.0     7.0           5.0           7.0
933       6.0            6.0       5.0     7.0           6.0           7.0
934       6.0            6.0       7.0     7.0           7.0           7.0
935       6.0            5.0       6.0     6.0           6.0           NaN
936       6.0            5.0       NaN     5.0           5.0           NaN
937       NaN            5.0       6.0     5.0           NaN           6.0
938       5.0            NaN       7.0     NaN           NaN           5.0
939       5.0            6.0       NaN     7.0           5.0           6.0
940       5.0            NaN       NaN     6.0           7.0           NaN
941       5.0            NaN       NaN     6.0           5.0           NaN
942       NaN            5.0       5.0     7.0           NaN           5.0
943       NaN            5.0       NaN     6.0           5.0           6.0
944       6.0            NaN       5.0     6.0           NaN           NaN
945       5.0            NaN       5.0     6.0           6.0           5.0
946       6.0            NaN       5.0     6.0           NaN           NaN
947       NaN            6.0       5.0     7.0           5.0           6.0
948       NaN            NaN       6.0     5.0           NaN           5.0
949       6.0            NaN       6.0     7.0           6.0           5.0
950       6.0            5.0       7.0     7.0           5.0           5.0
951       NaN            NaN       NaN     NaN           NaN           5.0
952       5.0            6.0       6.0     7.0           NaN           6.0
953       NaN            6.0       5.0     7.0           NaN           NaN
954       5.0            5.0       5.0     5.0           5.0           NaN
955       5.0            NaN       NaN     5.0           6.0           6.0
956       5.0            6.0       7.0     7.0           6.0           7.0
957       5.0            5.0       6.0     6.0           6.0           6.0

[957 rows x 6 columns]

In [27]:
# since i have 6 fields starting from Relastic to conventional
# i will be creating dataframe so i am making this data frame from my csv file
# datafram are memory representation of csv file into python so why i am creating it because i want to use 
# it provides functionalites such as analyze, change, and extract valuable information from the given dataset.
# https://towardsdatascience.com/pandas-dataframe-a-lightweight-intro-680e3a212b96

In [28]:
df

     Relastic  Investigative  Artistic  social  Enterprising  conventional
1           5              3         4       2             3             2
2           6              4         7       7             6             7
3           6              5         6       5             4             6
4           5              2         6       7             6             5
5           3              5         6       7             6             3
6           6              6         6       7             6             7
7           5              5         6       5             5             3
8           1              5         6       5             3             6
9           6              4         4       7             6             4
10          5              5         6       7             7             5
11          5              3         2       6             4             5
12          3              6         4       6             6             1
13          4              6         6       6             6             4
14          5              5         7       7             3             3
15          5              6         7       6             6             7
16          5              6         2       7             5             7
17          6              6         7       7             7             7
18          6              4         5       7             4             7
19          4              5         2       6             5             3
20          6              6         7       6             6             7
21          6              6         7       6             6             7
22          5              5         7       7             4             5
23          3              3         5       6             6             2
24          5              6         7       7             5             6
25          4              5         7       6             7             6
26          6              3         4       5             2             5
27          3              6         7       7             6             6
28          6              4         6       5             5             5
29          6              5         5       5             6             5
30          4              3         6       6             4             4
..        ...            ...       ...     ...           ...           ...
928         6              6         7       7             7             7
929         4              4         5       5             4             5
930         4              6         2       6             6             6
931         6              6         5       6             5             6
932         6              5         7       7             5             7
933         6              6         5       7             6             7
934         6              6         7       7             7             7
935         6              5         6       6             6             3
936         6              5         3       5             5             4
937         4              5         6       5             4             6
938         5              4         7       3             4             5
939         5              6         2       7             5             6
940         5              2         2       6             7             3
941         5              4         3       6             5             4
942         3              5         5       7             3             5
943         4              5         3       6             5             6
944         6              4         5       6             4             4
945         5              3         5       6             6             5
946         6              4         5       6             4             4
947         4              6         5       7             5             6
948         2              4         6       5             0             5
949         6              4         6       7             6             5
950         6              5         7       7             5             5
951         4              2         1       2             4             5
952         5              6         6       7             4             6
953         2              6         5       7             4             4
954         5              5         5       5             5             4
955         5              3         4       5             6             6
956         5              6         7       7             6             7
957         5              5         6       6             6             6

[957 rows x 6 columns]

In [29]:
#df['temp'] = df.index # temp is used to access index of dataframe

In [30]:
df.head()

   Relastic  Investigative  Artistic  social  Enterprising  conventional
1         5              3         4       2             3             2
2         6              4         7       7             6             7
3         6              5         6       5             4             6
4         5              2         6       7             6             5
5         3              5         6       7             6             3

In [61]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
X =df.iloc[:,[0,1]]
kmeans = KMeans(n_clusters=3, random_state=42)

In [62]:
Y_predict = kmeans.fit_predict(X)

In [65]:
print(Y_predict)  # this means all the clusters to which all the students belong

[1 0 0 1 2 0 0 2 0 0 1 2 2 0 0 0 0 0 2 0 0 0 1 0 2 1 2 0 0 1 0 1 1 1 1 1 0
 0 0 0 1 0 1 1 1 0 0 1 2 1 0 0 0 0 0 2 0 2 0 0 0 0 0 0 0 0 1 0 0 0 0 0 2 2
 2 1 0 1 1 0 2 0 1 1 0 1 0 0 0 0 0 0 0 0 2 0 1 2 0 2 0 2 0 0 0 0 0 2 0 0 0
 0 0 0 1 2 0 0 0 0 0 1 0 0 0 0 2 1 2 0 0 0 0 2 0 0 1 2 1 0 0 0 0 1 2 1 1 0
 0 0 1 1 0 0 2 2 0 0 0 0 0 2 0 0 0 0 2 0 0 0 1 0 1 2 1 1 2 0 0 0 0 0 1 0 0
 2 0 0 0 0 1 0 0 0 0 2 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 2 1 0 1 0 0 1 0 0 1
 2 0 0 0 0 2 1 0 1 0 0 0 0 0 0 0 0 0 0 2 1 0 2 2 0 0 0 2 0 0 0 0 0 0 2 0 0
 0 0 0 0 2 0 0 0 2 0 0 1 0 0 2 0 0 0 0 0 1 1 0 0 2 1 0 2 2 0 0 0 0 0 0 0 0
 2 0 1 0 0 0 2 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0 1 0 0 2 0 1 0 0 2 1 0 0 0 2 0
 1 0 0 0 1 2 0 1 0 0 0 2 2 0 2 1 0 1 1 0 0 2 2 2 0 1 0 2 0 2 0 0 0 0 0 1 0
 0 0 1 0 2 1 0 0 0 2 1 0 0 0 0 0 0 0 0 2 0 0 1 1 2 2 0 0 0 0 0 2 0 1 0 1 0
 2 2 0 0 2 0 1 0 1 1 2 0 0 2 2 0 1 0 0 1 1 0 0 2 1 0 0 0 2 0 0 0 0 0 2 0 0
 0 0 2 1 0 1 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 2 2 0 0 0 0 0 2
 0 0 0 0 0 0 0 2 1 0 0 2 0 0 0 0 0 0 2 0 2 0 0 0 0 0 1 0 1 0 2 0 0 0 0 0 1
 0 1 0 2 0 1 0 0 0 0 0 2 2 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 2 0 0 0 1 0 0 0 0
 1 2 0 1 0 2 2 1 1 0 0 0 1 1 0 0 0 0 2 0 0 1 0 0 2 0 0 2 0 0 0 0 1 0 0 0 0
 0 2 1 0 0 2 0 0 1 1 0 2 1 2 2 2 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0
 0 0 2 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 2 1 2 2 0 0 0 0 2 0
 2 0 2 2 0 0 0 0 0 2 0 2 0 2 0 0 1 0 2 0 1 2 1 2 2 0 2 2 2 0 2 0 1 0 0 0 2
 0 1 1 0 0 0 0 0 1 0 0 0 0 0 2 0 0 2 1 1 2 0 2 0 0 1 0 2 2 2 0 2 0 1 0 0 0
 1 0 0 1 1 0 0 1 0 0 1 0 0 2 1 1 0 2 0 0 0 0 0 0 0 0 2 0 0 0 0 1 0 1 2 0 0
 2 0 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 2 0 2 0 2 2
 0 1 0 1 0 1 1 1 2 0 1 0 1 0 0 0 0 2 1 0 1 0 0 1 2 0 2 0 1 0 1 0 1 0 2 1 2
 1 0 0 0 0 0 0 0 2 0 0 0 0 1 0 2 0 1 0 0 0 2 0 2 1 2 0 1 0 2 0 0 0 2 0 2 0
 0 0 1 2 1 0 2 2 0 2 0 1 0 2 0 1 1 2 0 1 0 2 0 0 0 0 1 1 0 1 1 0 2 0 2 2 0
 0 0 0 1 2 0 0 0 0 0 0 2 1 0 1 1 2 2 0 1 0 2 2 0 0 1 0 2 0 1 0 0]

In [ ]:
df.to_csv("C:\\Users\\Prashant\\Desktop\\collegedata\\Test2dataset\\datafram.csv")